#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

#xsetroot -solid '#081d3f'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-q close_or_remove
hc keybind $Mod-p spawn pavucontrol
hc keybind $Mod-Shift-q spawn xkill
hc keybind $Mod-Shift-r reload
hc keybind $Mod-BackSpace   spawn $HOME/scripts/rofi_exit.sh 
hc keybind $Mod-Return spawn "${TERMINAL:-alacritty}" # use your $TERMINAL with xterm as fallback

hc keybind $Mod-e spawn emacsclient -c
hc keybind $Mod-space spawn rofi -show drun
hc keybind $Mod-Control-s spawn flameshot gui
hc keybind $Mod-Control-z spawn ~/.screenlayout/fullhd.sh 
hc keybind $Mod-Control-x spawn ~/scripts/multimonitor_incremental_increase.sh

# audio
hc keybind $Mod-F1 spawn amixer -q -D pulse sset Master toggle
hc keybind XF86AudioRaiseVolume spawn amixer -q -D pulse sset Master 2%-
hc keybind XF86AudioLowerVolume spawn amixer -q -D pulse sset Master 2%+

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep
hc keybind $Mod-Shift-t floating toggle

# tags
#tag_names=( {1..9} )
tag_names=("1" "2" "3" "4" "5" "6" "7" "8" "9" )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-t floating toggle
hc keybind $Mod-f fullscreen toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-Shift-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent


##########################
## Macropad keybindings ##
##########################
    
    # PlaidPad                     
    # ,-----------------------,   
    # |  1  |  2  |  3  | Enc |  Encoder for system volume and play/pause
    # |-----+-----+-----+-----| 
    # |  4  |  5  |  6  |  7  | 
    # |-----+-----+-----+-----| 
    # |  8  |  9  | 10  |  11 | 
    # |-----+-----+-----+-----| 
    # |  12 |  13 | 14  |  15 |  
    # `-----------------------' 
    #
# 1
hc keybind $Mod+Mod1+0 spawn $HOME/scripts/multimonitor_incremental_increase.sh
# 2
hc keybind $Mod+Mod1+1 spawn 
# 3
hc keybind $Mod+Mod1+2 
# 4
hc keybind $Mod+Mod1+3
# 5
hc keybind $Mod+Mod1+4
# 6
hc keybind $Mod+Mod1+5
# # 7
hc keybind $Mod+Mod1+6
# # 8
hc keybind $Mod+Mod1+7
# # 9
hc keybind $Mod+Mod1+8 spawn screenkey
# # 10
hc keybind $Mod+Mod1+9 spawn killall -q screenkey
# # 11
hc keybind $Mod+Mod1+y spawn $HOME/scripts/restart_teams.sh
# # 12
hc keybind $Mod+Mod1+u spawn 
# # 13
hc keybind $Mod+Mod1+i spawn $HOME/scripts/toggle_dunst
# # 14
hc keybind $Mod+Mod1+o spawn $HOME/scripts/rofi_burton.sh
# # 15
hc keybind $Mod+Mod1+p spawn $HOME/scripts/toggle_pipewire_sink.sh

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set always_show_frame 1
hc set frame_border_active_color '#98be65'      #green
hc set frame_border_normal_color '#1e2127'      #black
hc set frame_bg_normal_color '#1e2127'          #grey
hc set frame_bg_active_color '#98be65'          #green

# hc set frame_bg_transparent 85
# hc set frame_transparent_width 20
hc set frame_gap 0
# hc set frame_active_opacity 50
# hc set frame_normal_opacity 50
hc set frame_border_width 0
hc set frame_border_inner_width 0
hc set frame_normal_opacity 20
hc set frame_active_opacity 0

# hc attr theme.active.color '#98be65' #green
hc attr theme.normal.color '#51afef' #blue
hc attr theme.urgent.color '#ff6c6b' #red
hc attr theme.inner_width 3
hc attr theme.inner_color '#1e2127' #black
hc attr theme.border_width 3
hc attr theme.floating.border_width 3
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color '#000000' #black
hc attr theme.active.inner_color '#98be65' #green
# hc attr theme.active.outer_color '#98be65' #green
hc attr theme.normal.inner_color '#da8548' #darkorange
# hc attr theme.background_color '#98be65' #green


hc set window_gap 8
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

hc set swap_monitors_to_get_tag 1
hc set raise_on_focus 1
hc set focus_follows_mouse 0

update_dragged_clients 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
# hc rule class=firefox tag=2
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class=''

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
#hc set_monitors 1280x1024+0+0 1280x1024+1280+0 1280x1024+1280+0
# or simply:
hc detect_monitors
#herbstclient set auto_detect_monitors 1

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    dunstify "$monitor"
    # "$panel" $monitor &
    # hc pad $monitor 20 &
done;
$HOME/.config/polybar/launch.sh 

#Autostart

blueman-applet
fix_xcursor
nm-applet
pa-applet
pamac-tray
keynav
killall volumeicon && hc volumeicon
xidlehook --not-when-fullscreen --not-when-audio --timer 1800 "betterlockscreen --off 5 -l dimblur"
xfce4-power-manager
spawn $HOME/scripts/multimonitor_incremental_increase.sh

