wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    clocks_a:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Vancouver: "America/Vancouver"
        Toronto: "America/Toronto"
        New_York: "America/New_York"
        Los_Angeles: "America/Los_Angeles"
        Stockholm: "Europe/Stockholm"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
      title: "World Time"
      type: "clocks"
    hackernews:
      enabled: true
      numberOfStories: 10
      position:
        top: 0
        left: 1
        height: 1
        width: 3
      storyType: top
      refreshInterval: 900
    git:
      commitCount: 5
      commitFormat: "[forestgreen]%h [grey]%cd [white]%s [grey]%an[white]"
      dateFormat: "%H:%M %d/%m"
      enabled: true
      position:
        top: 1
        left: 0
        height: 2
        width: 3
      refreshInterval: 8
      repositories:
        - "/home/gustav/code/blapp-front"
        - "/home/gustav/code/AnnualReportWeb"
    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 1
        left: 3
        height: 2
        width: 2
      refreshInterval: 1
      showCPU: true
      showMem: true
      showSwp: true
    jira:
      apiKey: "PMsWU6mcUU8s1IUjX1DsCE99"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "https://blinfo.atlassian.net"
      jql: 'project=BLAPP AND (status!=Resolved AND status!=Done AND status!="Ready for release" AND status!=Rejected AND status!=Archive ) AND assignee=5b7d007abfe3ea55c82c3159'
      email: "gustav.holmsten@blinfo.se"
      enabled: true
      position:
        top: 3
        left: 0
        height: 2
        width: 3
      project: "BLAPP"
      refreshInterval: 900
      username: "Gustav Holmsten"
      verifyServerCertificate: true
    uptime:
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 3
        left: 3
        height: 2
        width: 1
      refreshInterval: 30
      type: cmdrunner
    prettyweather:
        enabled: true
        city: "hudiksvall"
        position:
            top: 5
            left: 0
            height: 1
            width: 1
        refreshInterval: 300
        unit: "m"
        view: 0
        language: "en"
    ip:
          type: ipinfo
          title: "My IP"
          colors:
            name: "lightblue"
            value: "white"
          enabled: true
          position:
            top: 5
            left: 1
            height: 1
            width: 2
          refreshInterval: 150
    battery:
          type: power
          title: "Battery️"
          enabled: true
          position:
            top: 5
            left: 3
            height: 1
            width: 1
          refreshInterval: 15
