name: "Gustav"
color: '#46D9FF'
webhook_url: "https://bjornlunden.webhook.office.com/webhookb2/7886760a-086c-46dd-94a8-2b9f7c06a323@37a49a16-b27c-4909-9891-338b46379b9d/IncomingWebhook/c62a94464d0a41449e81c1532de783b6/6ed56d09-f5ec-436d-bb8f-3eab70628abf"
notifications: true
vab_msg: "Hela eller en delmängd min avkomma har vissnat i okänd omfattning, så jag blir vabbande"
report:
  path: /home/gustav/.butlerburton/
  update: true
  checkin_col: "C"
  checkout_col: "D"
  lunch_col: "F"
  bl_lunch_col: "I"
  overtime_col: "R"
  vab_col: "L"
  afk_col: "G"
