#!/usr/bin/env bash

pacmd set-default-source alsa_input.usb-Generic_Blue_Microphones_2036BAB06BE8-00.analog-stereo
pacmd set-default-sink bluez_sink.28_11_A5_DA_3A_96.headset_head_unit
pacmd set-card-profile bluez_card.28_11_A5_DA_3A_96 a2dp_sink
pacmd set-card-profile alsa_card.pci-0000_00_1f.3 off
